### ISSUE TITLE
Repository [...] changed its 'Suite' value from 'testing' to 'stable'

### ISSUE THREAD

**Issue by dezmob** [raphaelyancey/Virtual_FM_Band#5] opened 2019-07-11 20:29 UTC
When running the install script on buster :

```
pi@raspberrypi:~ $ sudo curl https://raw.githubusercontent.com/raphaelyancey/Virtual_FM_Band/master/install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1284  100  1284    0     0   2583      0 --:--:-- --:--:-- --:--:--  2578

[•] Upgrading and installing required packages

Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Get:2 http://raspbian.raspberrypi.org/raspbian buster InRelease [15.0 kB]
Reading package lists... Done
E: Repository 'http://raspbian.raspberrypi.org/raspbian buster InRelease' changed its 'Suite' value from 'testing' to 'stable'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
```

I solved this issue by changing app `apt-get` call to simply `apt`

**Comment by raphaelyancey** [comment] 2019-07-17 17:14
The install script seems to be broken with the recent release of Buster. I'll look into it, thanks for the feedback. Should still work with Stretch though.

**Comment by raphaelyancey** [comment] 2019-07-24 11:42
I cannot reproduce with a fresh Raspbian Buster image. What is the context of the installation? Likely a Stretch upgraded to Buster? Also see http://eriberto.pro.br/blog/2019/07/07/debian-repository-changed-its-suite-value-from-testing-to-stable/

**Comment by dezmob** [comment] 2019-07-24 11:50
I'll retry it ASAP with a fresh install of Buster (it was a clean install using the 2019-06-20-raspbian-buster image)

**Comment by culverit** [comment] 2019-07-28 02:22
I had the same issue with a fresh install, running
`sudo apt update -y`
fixed it for me.

**Comment by raphaelyancey** [comment] 2019-07-28 11:38
@culverit On a Raspberry Pi? If yes, which one? And which version of Raspbian exactly? Thanks.

**Comment by culverit** [comment] 2019-08-01 05:18
@raphaelyancey On a 3 B+ using a fresh buster image, not an upgrade from stretch

**Comment by raphaelyancey** [comment] 2019-08-01 09:32
I retried yesterday and still couldn't reproduce with the same setup (3B+, fresh Buster image). 

Anyway, I think it should be fixed with the next Raspbian release (https://www.raspberrypi.org/forums/viewtopic.php?t=245022#p1502863). I'll close the issue until then. If you have some time to test it then, and still face the problem, I'll re-open it.

**Closed as completed by raphaelyancey** 2019-08-01 09:32 UTC
Labels: bug
